FROM node:18

# Install dependencies
RUN apt-get update && apt-get install -y \
    vim \
    zip \
    unzip \
    curl




# Change current user
# USER node

EXPOSE 5173

# CMD ["npm start"]
# https://github.com/vitejs/vite/discussions/3396

# CMD ["sh", "-c", "npm run dev -- --host"] 

# govno ne rabotaet
# CMD ["sh", "-c", "npm install && npm run dev -- --host"] 